# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\PycharmProjects\ya3\addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddEditCoffeeForm(object):
    def setupUi(self, AddEditCoffeeForm):
        AddEditCoffeeForm.setObjectName("AddEditCoffeeForm")
        self.verticalLayout = QtWidgets.QVBoxLayout(AddEditCoffeeForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.nameLineEdit = QtWidgets.QLineEdit(AddEditCoffeeForm)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.verticalLayout.addWidget(self.nameLineEdit)
        self.descriptionTextEdit = QtWidgets.QTextEdit(AddEditCoffeeForm)
        self.descriptionTextEdit.setObjectName("descriptionTextEdit")
        self.verticalLayout.addWidget(self.descriptionTextEdit)
        self.priceLineEdit = QtWidgets.QLineEdit(AddEditCoffeeForm)
        self.priceLineEdit.setObjectName("priceLineEdit")
        self.verticalLayout.addWidget(self.priceLineEdit)
        self.saveButton = QtWidgets.QPushButton(AddEditCoffeeForm)
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout.addWidget(self.saveButton)

        self.retranslateUi(AddEditCoffeeForm)
        QtCore.QMetaObject.connectSlotsByName(AddEditCoffeeForm)

    def retranslateUi(self, AddEditCoffeeForm):
        _translate = QtCore.QCoreApplication.translate
        self.nameLineEdit.setPlaceholderText(_translate("AddEditCoffeeForm", "Имя кофе"))
        self.descriptionTextEdit.setPlaceholderText(_translate("AddEditCoffeeForm", "Описание кофе"))
        self.priceLineEdit.setPlaceholderText(_translate("AddEditCoffeeForm", "Цена кофе"))
        self.saveButton.setText(_translate("AddEditCoffeeForm", "Сохранить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddEditCoffeeForm = QtWidgets.QDialog()
    ui = Ui_AddEditCoffeeForm()
    ui.setupUi(AddEditCoffeeForm)
    AddEditCoffeeForm.show()
    sys.exit(app.exec_())
