# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\PycharmProjects\ya3\UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.addEditButton = QtWidgets.QPushButton(self.centralwidget)
        self.addEditButton.setObjectName("addEditButton")
        self.verticalLayout.addWidget(self.addEditButton)
        self.nameLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.verticalLayout.addWidget(self.nameLineEdit)
        self.descriptionTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.descriptionTextEdit.setObjectName("descriptionTextEdit")
        self.verticalLayout.addWidget(self.descriptionTextEdit)
        self.priceLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.priceLineEdit.setObjectName("priceLineEdit")
        self.verticalLayout.addWidget(self.priceLineEdit)
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout.addWidget(self.saveButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.pushButton.setText(_translate("MainWindow", "Рисовать"))
        self.addEditButton.setText(_translate("MainWindow", "Добавить/Редактировать"))
        self.nameLineEdit.setPlaceholderText(_translate("MainWindow", "Имя кофе"))
        self.descriptionTextEdit.setPlaceholderText(_translate("MainWindow", "Описание кофе"))
        self.priceLineEdit.setPlaceholderText(_translate("MainWindow", "Цена кофе"))
        self.saveButton.setText(_translate("MainWindow", "Сохранить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
